# from no_terminales import no_terminales as NT

tabla_parser = {
    
}
    


# INSTRUCCION -> _INTRUCCION INSTRUCCION
# INSTRUCCION -> ''


# _INTRUCCION -> DECLARACION ;
# _INTRUCCION -> id ID ;
# _INTRUCCION -> RETURN_I ;

# ID -> D_INIT
# ID -> FUNTION_CALL

# TIPO -> int
# TIPO -> float
# TIPO -> char

# RETURN_I -> return "expresion"

# FUNTION_CALL -> ( ARGUMENT )

# ARGUMENT -> "expresion" A_ARGUMENT
# ARGUMENT -> ''

# A_ARGUMENT -> , "expresion" A_ARGUMENT
# A_ARGUMENT -> ''


# DECLARACION -> TIPO id D_INIT
# D_INIT -> = "expresion"
# D_INIT -> = ''
